Update to Blog
nhsx/AnalyticsUnit pull request #20
Opened 2021-12-30 13:51 UTC by JRPearson500

2021-12-30 13:52 UTC, JRPearson500 commented
Added further details on quality metrics off the back of Dom's and Jennifer's work and references to more recent work.

2022-01-07 11:07 UTC, danjscho requested changes
Typos to fix, but looks good aside from that.

2022-01-07 11:07 UTC, danjscho commented on synthetic.md
> +* **Statistical Distribtuion Comparisons** such as Gaussian mixture log liklihood; Kolmogoroc-Smirnov test for comparing the cumulative distribution function of two continuous variables and the chi-s
Typo - `liklihood` -> `likelihood`

2022-01-07 11:07 UTC, danjscho commented on synthetic.md
> +* **Statistical Outcome Comparisons** such as [Voas Williamson statistic](https://onlinelibrary.wiley.com/doi/abs/10.1002/1099-1220%28200009/10%296%3A5%3C349%3A%3AAID-IJPG196%3E3.0.CO%3B2-5) (measure
Typo - `divergenece` -> `divergence`

2022-01-07 11:07 UTC, danjscho commented on synthetic.md
> +* **Off-Manifold and Latent Space checks** - consider using principal component analysis (PCA) or [t-distributed stochastic neighbor embedding](https://distill.pub/2016/misread-tsne/) (t-SNE) to visu
US spelling? - `neighbor` -> `neighbour`

2022-03-07 14:44 UTC, danjscho commented on synthetic.md
> +An NHSX Data Science Intern Project focussed on developing an open source tool for generating medium fidelity data with high privacy.  USes the PyTorch implmentation of SGD-DP.
`USes` -> `uses`

2022-03-07 14:45 UTC, danjscho commented on synthetic.md
>  The Synthetic Data Vault project has a section on [Evaluation Framework](https://sdv.dev/SDV/user_guides/evaluation/evaluation_framework.html) built in python which includes a small suite of function
`Synthetic Data Vault` -> `Synthetic Data Vault (SDV)`

2022-03-07 14:46 UTC, danjscho commented on synthetic.md
> +Although all these tests are useful, none give a definitive metric which can be tested against.  **Differential Privacy** is the most established mathematical way of defining some level of privacy in
`Stochastic` -> `stochastic`

2022-04-06 14:27 UTC, merged